from .BceGAN import BceGAN
from .BceGAN_ALP import BceGAN_ALP
from .BceGAN_GP import BceGAN_GP
from .CramerGAN import CramerGAN
from .GAN import GAN
from .LSGAN import LSGAN
from .WGAN import WGAN
from .WGAN_ALP import WGAN_ALP
from .WGAN_GP import WGAN_GP
